sudo: false
language: shell
before_script:
  - npm install -g wt-cli
script:
- make dist-addon
- make deploy-webtask
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: b0zeQrEgxAdfBprRFC7tFk8b6+Lk0hRbmAoDrfZ4NWWN1+Jt/Zf53QOCAW/MiayF8THTb7nyIBid9wXnELvV++ZQE7IzWUhr7VIIPxuWlObBnePyTjZMwcVGqhq+1jfpoAAtnkOYl+tKX74NgLvqyK6v4qLr5JwJnmxrHO2aBelYtgkyAYH9aKBWNDyVXhhK5A/INNpt+65X5+HJij0O/tktlSXqXv2VeXWW+rjrjjaeYpmyUkezTjYWgdTSxFq2gKq+dmNwl6tlJJxODtsXOmqW8xEElePK0h+a8kOWKk1b1cpEKmT4zzHmPAGUipYPOvqcRJdBc44aX7wR7Zm49migBN6be8Rxb6Em3Z0LXqUq3sPcMHh1wW3D3nVzM9HuINIU1odonIpLpO+WenGg02wSO6KLO3/x8VsICsNaF+fETBRXRGiXEO5+i7hamokz27CxSEE//LD8+Et/ebP3xogWeri1mT7iDYYXfWiOOekReuLr/F2wBfuETlNzTDkJkCfaSfLLt4YUba68FloqR71TCAuBCx58FoCmV+NevM0oXws8QcxeVFfiqAbYnBn6hjSb39om330FbR9XHwDh2UWhFB8nxJxwqv2QZMUWHpQhOZFH4SgQOZM1dC5+nZfMXQ6noiyKp7AFgsNxwOotqMhXp3o783zh0kw+FW3jw+8=
  file: script.timewasted*.zip
  on:
    repo: dominis/test-auth0
